import type { ToolDefinition, JSONSchemaProperty } from "../types";

/**
 * Convert a tool name to PascalCase for TypeScript interface naming.
 */
function toPascalCase(name: string): string {
  return name
    .split(/[_-]/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

/**
 * Convert a JSON Schema type to TypeScript type.
 */
function jsonSchemaTypeToTypeScript(
  prop: JSONSchemaProperty,
  isRequired: boolean
): string {
  let baseType: string;

  switch (prop.type) {
    case "string":
      if (prop.enum && prop.enum.length > 0) {
        baseType = prop.enum.map((v) => `"${v}"`).join(" | ");
      } else {
        baseType = "string";
      }
      break;
    case "number":
    case "integer":
      baseType = "number";
      break;
    case "boolean":
      baseType = "boolean";
      break;
    case "array":
      if (prop.items) {
        const itemType = jsonSchemaTypeToTypeScript(prop.items, true);
        baseType = `${itemType}[]`;
      } else {
        baseType = "unknown[]";
      }
      break;
    case "object":
      if (prop.properties) {
        const props = Object.entries(prop.properties)
          .map(([k, v]) => {
            const propRequired = prop.required?.includes(k) ?? false;
            const propType = jsonSchemaTypeToTypeScript(v, propRequired);
            const opt = propRequired ? "" : "?";
            return `${k}${opt}: ${propType}`;
          })
          .join("; ");
        baseType = `{ ${props} }`;
      } else {
        baseType = "Record<string, unknown>";
      }
      break;
    default:
      baseType = "unknown";
  }

  return isRequired ? baseType : `${baseType} | undefined`;
}

/**
 * Generate the Arguments interface for a tool.
 */
function generateArgsInterface(tool: ToolDefinition): string {
  const interfaceName = `${toPascalCase(tool.name)}Args`;
  const properties = tool.parameters.properties;
  const required = new Set(tool.parameters.required || []);

  const fields = Object.entries(properties)
    .map(([name, prop]) => {
      const tsType = jsonSchemaTypeToTypeScript(prop, required.has(name));
      const optional = required.has(name) ? "" : "?";
      const description = prop.description
        ? `  /** ${prop.description} */\n`
        : "";
      return `${description}  ${name}${optional}: ${tsType};`;
    })
    .join("\n");

  return `/**
 * Arguments for the ${tool.name} tool.
 */
export interface ${interfaceName} {
${fields}
}`;
}

/**
 * Generate the ToolHandlers type.
 */
function generateToolHandlersType(tools: ToolDefinition[]): string {
  if (tools.length === 0) {
    return `/**
 * Handler functions for registered tools.
 * No tools are configured - add tools to your app.config.js.
 */
export type ToolHandlers = Record<string, never>;`;
  }

  const handlers = tools
    .map((tool) => {
      const argsType = `${toPascalCase(tool.name)}Args`;
      return `  /**
   * Handler for the ${tool.name} tool.
   * ${tool.description}
   */
  ${tool.name}: (args: ${argsType}) => Promise<string> | string;`;
    })
    .join("\n\n");

  return `/**
 * Handler functions for registered tools.
 * Each handler receives typed arguments and must return a string result.
 */
export interface ToolHandlers {
${handlers}
}`;
}

/**
 * Generate the tool names type.
 */
function generateToolNamesType(tools: ToolDefinition[]): string {
  if (tools.length === 0) {
    return `/**
 * Union type of all registered tool names.
 */
export type ToolName = never;`;
  }

  const names = tools.map((t) => `"${t.name}"`).join(" | ");

  return `/**
 * Union type of all registered tool names.
 */
export type ToolName = ${names};`;
}

/**
 * Generate the complete TypeScript file with all tool types.
 */
export function generateTypeScriptTools(tools: ToolDefinition[]): string {
  const header = `// Generated by react-native-foundation-models
// Do not edit this file directly. Modify your tool configuration in app.config.js instead.

`;

  if (tools.length === 0) {
    return `${header}${generateToolNamesType(tools)}

${generateToolHandlersType(tools)}
`;
  }

  const argsInterfaces = tools.map(generateArgsInterface).join("\n\n");
  const toolNamesType = generateToolNamesType(tools);
  const handlersType = generateToolHandlersType(tools);

  return `${header}${argsInterfaces}

${toolNamesType}

${handlersType}
`;
}
