// Generated by react-native-foundation-models
// This file is regenerated during `expo prebuild` based on your tool configuration in app.config.js
// Do not edit this file directly.

import Foundation
import FoundationModels

// No tools configured.
// Add tools to your app.config.js plugin configuration to generate tool implementations here.

/// Creates a LanguageModelSession with the generated tools.
@available(iOS 26.0, *)
func createSessionWithTools(
    model: SystemLanguageModel,
    instructions: String?,
    bridge _: ToolBridge)
-> LanguageModelSession {
    if let instructions {
        return LanguageModelSession(model: model, instructions: instructions)
    } else {
        return LanguageModelSession(model: model)
    }
}

/// Returns true if there are generated tools configured.
@available(iOS 26.0, *)
func hasGeneratedTools() -> Bool {
    false
}
